#!/usr/bin/env bash
# Render postiz.env from QuantGist sm_credential.md (run locally on Mac only).
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
CREDS="${QG_SM_CREDENTIALS:-/Users/nanabee_home/.openclaw/workspace/workspace_QuantGist/Quantgist_setup/social_media/sm_credential.md}"
OUT="${INFRA_DIR}/postiz.env"

if [[ ! -f "$CREDS" ]]; then
  echo "Missing credentials file: $CREDS" >&2
  exit 1
fi

read_var() {
  local pattern="$1"
  # Skip comment lines, then match the first assignment for this key.
  grep -v '^[[:space:]]*#' "$CREDS" \
    | grep -E "(${pattern})[[:space:]]*[=:]" | head -1 \
    | sed -E 's/^[^=:]+[=:][[:space:]]*//' | tr -d '\r' \
    | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'
}

# Postiz X provider uses OAuth 1.0a Consumer Key/Secret — not OAuth 2.0 Client ID.
X_API_KEY="$(read_var 'X_Consumer_key')"
X_API_SECRET="$(read_var 'X_Secret_key')"
LINKEDIN_CLIENT_ID="$(read_var 'Linkedin_Client_ID')"
LINKEDIN_CLIENT_SECRET="$(read_var 'Client_secret')"
LINKEDIN_PAGE_CLIENT_ID="$(read_var 'LinkedIn_Page_Client_ID')"
LINKEDIN_PAGE_CLIENT_SECRET="$(read_var 'LinkedIn_Page_Client_Secret')"
FACEBOOK_APP_ID="$(read_var 'FACEBOOK_APP_ID|FB_App_ID|Facebook_App_ID')"
FACEBOOK_APP_SECRET="$(read_var 'FACEBOOK_APP_SECRET|FB_App_Secret|Facebook_App_Secret')"

if [[ -f "$OUT" ]]; then
  JWT_SECRET="$(grep -E '^JWT_SECRET=' "$OUT" | head -1 | cut -d= -f2-)"
fi
if [[ -z "${JWT_SECRET:-}" ]]; then
  JWT_SECRET="$(openssl rand -hex 32)"
fi

cat > "$OUT" << EOF
# Generated by render-postiz-env.sh — do not commit
MAIN_URL=https://smm.quantgist.com
FRONTEND_URL=https://smm.quantgist.com
NEXT_PUBLIC_BACKEND_URL=https://smm.quantgist.com/api
BACKEND_INTERNAL_URL=http://localhost:3000
JWT_SECRET=${JWT_SECRET}
DATABASE_URL=postgresql://postiz-user:postiz-password@postiz-postgres:5432/postiz-db-local
REDIS_URL=redis://postiz-redis:6379
TEMPORAL_ADDRESS=temporal:7233
IS_GENERAL=true
DISABLE_REGISTRATION=false
RUN_CRON=true
STORAGE_PROVIDER=local
UPLOAD_DIRECTORY=/uploads
NEXT_PUBLIC_UPLOAD_DIRECTORY=/uploads
API_LIMIT=90
X_API_KEY=${X_API_KEY}
X_API_SECRET=${X_API_SECRET}
LINKEDIN_CLIENT_ID=${LINKEDIN_CLIENT_ID}
LINKEDIN_CLIENT_SECRET=${LINKEDIN_CLIENT_SECRET}
LINKEDIN_PAGE_CLIENT_ID=${LINKEDIN_PAGE_CLIENT_ID}
LINKEDIN_PAGE_CLIENT_SECRET=${LINKEDIN_PAGE_CLIENT_SECRET}
FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}
EOF

chmod 600 "$OUT"
echo "Wrote ${OUT}"

missing=()
[[ -z "${X_API_KEY}" ]] && missing+=("X_Consumer_key")
[[ -z "${X_API_SECRET}" ]] && missing+=("X_Secret_key")
[[ -z "${LINKEDIN_CLIENT_ID}" ]] && missing+=("Linkedin_Client_ID")
[[ -z "${LINKEDIN_CLIENT_SECRET}" ]] && missing+=("Client_secret")
[[ -z "${LINKEDIN_PAGE_CLIENT_ID}" ]] && missing+=("LinkedIn_Page_Client_ID")
[[ -z "${LINKEDIN_PAGE_CLIENT_SECRET}" ]] && missing+=("LinkedIn_Page_Client_Secret")
[[ -z "${FACEBOOK_APP_ID}" ]] && missing+=("FACEBOOK_APP_ID")
[[ -z "${FACEBOOK_APP_SECRET}" ]] && missing+=("FACEBOOK_APP_SECRET")

if [[ ${#missing[@]} -gt 0 ]]; then
  echo "WARN: empty credential fields in sm_credential.md: ${missing[*]}" >&2
  echo "      Facebook OAuth needs FACEBOOK_APP_ID + FACEBOOK_APP_SECRET (Meta Developer app)." >&2
  echo "      X connect needs valid OAuth 1.0a Consumer Key/Secret (not X_Client_ID)." >&2
fi
